"""changed list columns to JSON

Revision ID: 70277ba04f69
Revises: a453043bcc80
Create Date: 2024-06-17 10:31:57.067592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70277ba04f69'
down_revision = 'a453043bcc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preset', schema=None) as batch_op:
        batch_op.alter_column('styles',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('include_columns',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('styles',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('styles',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('include_columns',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('preset', schema=None) as batch_op:
        batch_op.alter_column('styles',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
