"""added admin column to Users

Revision ID: 848daa9b2115
Revises: 70277ba04f69
Create Date: 2024-06-24 11:12:26.546980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848daa9b2115'
down_revision = '70277ba04f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
